In [1]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
import numpy as np

# Зомолт Ясир, ФІТ 4-8, Варіан 11
# Завдання 1
# Створіть одновимірний масив (вектор) із арифметичною послідовністю, де кожне наступне число більше попереднього на 5, починаючи з 3, та виведіть його значення.



start = 3
step = 5
size = 10  # Задаємо розмір масиву

array = np.arange(start, start + step * size, step)
array

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [4]:
# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його добутками кожного числа та його попереднього, починаючи з 1, та виведіть його значення.

matrix_size = 3
elements = np.arange(1, matrix_size**2 + 1)
matrix = np.array([elements[i] * (elements[i] - 1) for i in range(len(elements))]).reshape(matrix_size, matrix_size)
matrix

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [5]:
# Завдання 3
# Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від 1 до 2 та знайдіть середнє арифметичне його елементів.

random_matrix = np.random.randint(1, 3, size=(3, 3))
mean_value = np.mean(random_matrix)

random_matrix, mean_value

(array([[1, 2, 2],
        [1, 1, 1],
        [2, 1, 2]]),
 1.4444444444444444)

In [6]:
# Завдання 4
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.

random_matrix_4x4 = np.random.rand(4, 4)
count_greater_than_0_5 = np.sum(random_matrix_4x4 > 0.5)

random_matrix_4x4, count_greater_than_0_5


(array([[0.65925149, 0.37292879, 0.65113389, 0.4436119 ],
        [0.39873128, 0.02663052, 0.38246612, 0.86715846],
        [0.78947746, 0.38815741, 0.31398561, 0.46350127],
        [0.18129042, 0.17821134, 0.297875  , 0.29530576]]),
 4)

In [7]:
# Завдання 5
# Створіть два одновимірних масиви розміром 7, заповніть їх випадковими цілими числами від -15 до 15 та виконайте на них поелементні операції додавання, віднімання та множення.
array1 = np.random.randint(-15, 16, size=7)
array2 = np.random.randint(-15, 16, size=7)

addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2

array1, array2, addition_result, subtraction_result, multiplication_result


(array([ 2,  3, -6, 11,  9, -7, -9]),
 array([  6,   0,  -6, -11,   5,  13,  -5]),
 array([  8,   3, -12,   0,  14,   6, -14]),
 array([ -4,   3,   0,  22,   4, -20,  -4]),
 array([  12,    0,   36, -121,   45,  -91,   45]))

In [8]:
import numpy as np

# Завдання 6
# Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

product_matrix = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)
print("\nДобуток матриць:")
print(product_matrix)


Матриця 1:
[[ 6  1  1  4]
 [ 4  1 10  3]
 [ 2  5  3  5]
 [10  1  4  2]]

Матриця 2:
[[ 4 10  2  6]
 [ 4 10  2  8]
 [10  3  6  3]
 [ 8  1  9  5]]

Добуток матриць:
[[ 70  77  56  67]
 [144  83  97  77]
 [ 98  84  77  86]
 [100 124  64  90]]


In [9]:
# Завдання 7
# Створіть дві матриці розміром 4x2 та 2x5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

matrix_4x2 = np.random.randint(1, 11, size=(4, 2))
matrix_2x5 = np.random.randint(1, 11, size=(2, 5))

product_matrix_4x5 = np.dot(matrix_4x2, matrix_2x5)

matrix_4x2, matrix_2x5, product_matrix_4x5


(array([[8, 2],
        [8, 9],
        [7, 6],
        [6, 2]]),
 array([[ 6,  9,  3,  8,  3],
        [ 4,  1, 10,  9,  5]]),
 array([[ 56,  74,  44,  82,  34],
        [ 84,  81, 114, 145,  69],
        [ 66,  69,  81, 110,  51],
        [ 44,  56,  38,  66,  28]]))

In [10]:
# Завдання 8
# Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.


matrix_2x2 = np.random.randint(1, 13, size=(2, 2))

# Перевірка, чи матриця має обернену (визначник не дорівнює нулю)
determinant = np.linalg.det(matrix_2x2)

if determinant != 0:
    inverse_matrix = np.linalg.inv(matrix_2x2)
else:
    inverse_matrix = "Матриця не має оберненої (визначник дорівнює нулю)."

matrix_2x2, inverse_matrix


(array([[ 7, 12],
        [ 7,  5]]),
 array([[-0.10204082,  0.24489796],
        [ 0.14285714, -0.14285714]]))

In [11]:
# Завдання 9
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

matrix_3x3 = np.random.rand(3, 3)
transposed_matrix = np.transpose(matrix_3x3)

matrix_3x3, transposed_matrix


(array([[0.33801596, 0.9334237 , 0.4275417 ],
        [0.93399766, 0.91244427, 0.43538894],
        [0.15781458, 0.44180822, 0.83745177]]),
 array([[0.33801596, 0.93399766, 0.15781458],
        [0.9334237 , 0.91244427, 0.44180822],
        [0.4275417 , 0.43538894, 0.83745177]]))

In [12]:
# Завдання 10
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1 і знайдіть добуток матриці на вектор.


matrix_3x4 = np.random.rand(3, 4)
vector_4x1 = np.random.rand(4, 1)

product_result = np.dot(matrix_3x4, vector_4x1)

matrix_3x4, vector_4x1, product_result

(array([[0.94806192, 0.14017704, 0.91146934, 0.54944625],
        [0.34393309, 0.69764363, 0.25367546, 0.94571439],
        [0.23791088, 0.13587482, 0.77520942, 0.24997375]]),
 array([[0.35655256],
        [0.00245506],
        [0.36861928],
        [0.35652912]]),
 array([[0.8702568 ],
        [0.55502736],
        [0.46004137]]))

In [13]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

matrix_2x3 = np.random.rand(2, 3)
vector_3 = np.random.randint(1, 11, size=3)

product_result = np.dot(matrix_2x3, vector_3)

matrix_2x3, vector_3, product_result


(array([[0.63245292, 0.63312074, 0.92142382],
        [0.09056676, 0.50200761, 0.87999135]]),
 array([1, 1, 4]),
 array([4.95126895, 4.11253977]))

In [14]:
# Завдання 12
# Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть різницю всіх елементів обох матриць.


matrix_4x4_a = np.random.randint(1, 11, size=(4, 4))
matrix_4x4_b = np.random.randint(1, 11, size=(4, 4))

difference_matrix = matrix_4x4_a - matrix_4x4_b

matrix_4x4_a, matrix_4x4_b, difference_matrix

(array([[ 3,  2,  1, 10],
        [ 9,  2,  6,  9],
        [ 5,  5,  3,  7],
        [ 2,  3,  1, 10]]),
 array([[ 2,  6,  4,  6],
        [10,  9,  9,  1],
        [ 5,  8,  3,  8],
        [ 4,  2,  4,  6]]),
 array([[ 1, -4, -3,  4],
        [-1, -7, -3,  8],
        [ 0, -3,  0, -1],
        [-2,  1, -3,  4]]))

In [15]:
# Завдання 13
# Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть суму їх елементів.

matrix_3x3_a = np.random.uniform(-1, 1, size=(3, 3))
matrix_3x3_b = np.random.uniform(-1, 1, size=(3, 3))

sum_matrix_a = np.sum(matrix_3x3_a)
sum_matrix_b = np.sum(matrix_3x3_b)

matrix_3x3_a, sum_matrix_a, matrix_3x3_b, sum_matrix_b


(array([[-0.11570866, -0.67636762,  0.73569225],
        [ 0.58097895, -0.91702442, -0.31025821],
        [-0.68451241,  0.51789891,  0.31980065]]),
 -0.5495005527199881,
 array([[-0.28353314, -0.99038449,  0.56112201],
        [ 0.48413692, -0.81545854,  0.29661782],
        [ 0.02804563,  0.73106596, -0.60523172]]),
 -0.59361956978523)

In [16]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -3 до 3 та знайдіть кількість парних елементів матриці.

matrix_3x3 = np.random.uniform(-3, 3, size=(3, 3))

# Для визначення парних елементів, спочатку округлимо значення до найближчих цілих і перевіримо їх на парність
rounded_matrix = np.round(matrix_3x3).astype(int)
even_count = np.sum(rounded_matrix % 2 == 0)

matrix_3x3, rounded_matrix, even_count


(array([[ 0.47904639, -1.40483131,  0.81849008],
        [-1.85342417, -0.65330765, -1.67959233],
        [ 0.7835102 , -0.9303033 ,  2.32905734]]),
 array([[ 0, -1,  1],
        [-2, -1, -2],
        [ 1, -1,  2]]),
 4)

In [17]:
from scipy.stats import gmean

# Завдання 15
# Створіть матрицю розміром 5x5, заповніть її випадковими дійсними числами в діапазоні від -0.5 до 0.5 та знайдіть вектор-стовпчик, що містить середнє геометричне значення елементів кожного рядка матриці.
matrix_5x5 = np.random.uniform(-0.5, 0.5, size=(5, 5))

# Для коректного обчислення середнього геометричного, всі елементи повинні бути додатніми.
# Тому будемо брати абсолютні значення, оскільки gmean не визначене для від'ємних чисел.
abs_matrix = np.abs(matrix_5x5)
geometric_mean_vector = gmean(abs_matrix, axis=1)

matrix_5x5, geometric_mean_vector


(array([[-0.21196894,  0.21692331, -0.3827809 ,  0.4172954 , -0.12151705],
        [-0.08234521,  0.46151839,  0.15629801, -0.13635198,  0.24405948],
        [ 0.28556476,  0.11762405,  0.00243906,  0.38387219,  0.37790686],
        [-0.39686774, -0.20094594, -0.04752793, -0.18627399, -0.44261441],
        [-0.44765743, -0.01241086, -0.324461  ,  0.31986454, -0.03076745]]),
 array([0.2455398 , 0.18163   , 0.10351398, 0.19905374, 0.11214852]))

In [18]:
# Висновок:
# Під час виконання цієї лабораторної роботи було розв'язано 15 завдань, що охоплюють різні операції з масивами та матрицями в Python за допомогою бібліотеки NumPy.
# Основні теми, що були охоплені:
# 1. Створення та маніпуляції з одновимірними та двовимірними масивами, зокрема створення арифметичних послідовностей, випадкових чисел, та виконання поелементних операцій.
# 2. Застосування лінійної алгебри, включаючи обчислення оберненої матриці, транспонування, множення матриць і векторів, та знаходження середнього геометричного.
# 3. Обчислення статистичних характеристик, таких як сума, кількість парних елементів, середнє арифметичне та геометричне значення.
# Всі завдання були виконані з використанням випадкових чисел у відповідних діапазонах, що дозволило проаналізувати різні операції над матрицями та векторами.
# Таким чином, ця робота допомогла закріпити навички роботи з масивами та матрицями в Python, а також розвинути розуміння різних математичних операцій, які можна застосовувати в чисельних обчисленнях.
